### ISSUE TITLE
STOCK: "Georges Bank haddock" 2 stockid

### ISSUE THREAD

**Issue by mcmelnychuk** [ramadmin/RLSADB#27]
There are two stockid's with the same stocklong. Please update one or the other stocklong.

Also check whether one is a subset of the other. If so, we do not want to include both in regional summary plots or global summary plots, to avoid double-counting.

More generally, do we have a flag for duplicate or overlapping stocks, or could you add one, with a variable that indicates priority of one over the other (e.g. first priority to the larger stock area definition). Then in regional and global summaries the duplicate stocks or smaller subset of stocks can be automatically excluded.

**Comment by mcmelnychuk** [comment]
I confirmed with Kristan Blackhart that the eastern GB stock is a nested subset of the GB stock. The same is true for Atlantic cod. So the two eastern GB stocks should not be included in the regional summaries (of summed biomass), otherwise that would be double-counting.

**Comment by ramadmin** [comment]
The eastern GB haddock assessments were removed with this version, but will be re-included but not flagged as current stocks (so they won't show up in summaries/views) in the coming version. We don't currently have any flags for duplicate/overlapping stocks, but I am thinking the mostrecent field in assessment can be adapted for this since its underutilized at the moment. Which atlantic cod assessments do you mean, I see only one associated with GB?
