### ISSUE TITLE
STOCK: Chub mackerel Pacic Coast of Japan (CMACKPJPN)

### ISSUE THREAD

**Issue by kurota** [ramadmin/RLSADB#5]
Reference point problem: Bmsy estimated by the production model is considered to be too high. This stock is known to show a climate-driven regime shift.

**Comment by mcmelnychuk** [comment]
Daniel, do we have an indicator variable associated with the surplus production fit for each stock so that we can manually flag fits that are considered to be unreliable? This would be best tied to the assessid, and any designations of fits considered unreliable should persist throughout future versions. 
The designation (flag) can indicate whether the fit is considered unreliable based on the filtering rules in place (which may update soon) or whether it's unreliabled based on visual inspection.

**Comment by ramadmin** [comment]
This should get resolved with the upcoming new production model fitting method/protocol.
